vim.keymap.set("n", "<leader>e", ":NvimTreeToggle <CR>", {})
vim.keymap.set("n", "<leader>E", ":NvimTreeFindFile <CR>", {})
vim.keymap.set("n", "<CR>", "<CR><Cmd>cclose<CR>", { buffer = false, noremap = true, silent = true })
vim.keymap.set("n", "<C-g>", ":LazyGit<CR>", {})
vim.keymap.set("x", "gr", ":Gitsigns reset_hunk<CR>", {})
vim.keymap.set("x", "gs", ":Gitsigns stage_hunk<CR>", {})
vim.keymap.set("x", "gp", ":Gitsigns preview_hunk_inline<CR>", {})
vim.keymap.set("x", "gb", ":Gitsigns toggle_current_line_blame<CR>", {})

vim.keymap.set("n", "Q", ":q<CR>", {})
