vim.keymap.set("n", "<leader>e", ":NvimTreeToggle <CR>", {})
vim.keymap.set("n", "<leader>E", ":NvimTreeFindFile <CR>", {})
vim.keymap.set("n", "<CR>", "<CR><Cmd>cclose<CR>", { buffer = false, noremap = true, silent = true })
vim.keymap.set("n", "<C-g>", ":LazyGit<CR>", {})
vim.keymap.set("x", "gr", ":Gitsigns reset_hunk<CR>", {})
vim.keymap.set("x", "gs", ":Gitsigns stage_hunk<CR>", {})
vim.keymap.set("x", "gp", ":Gitsigns preview_hunk_inline<CR>", {})
vim.keymap.set("x", "gb", ":Gitsigns toggle_current_line_blame<CR>", {})

vim.keymap.set("n", "<leader><leader>x", "<cmd>source %<CR>", {})
vim.keymap.set("n", "<leader>x", ":.lua<CR>", {})
vim.keymap.set("v", "<leader>x", ":lua<CR>", {})

vim.keymap.set("n", "Q", ":q<CR>", {})

vim.keymap.set("n", "<leader>1", "1gt")
vim.keymap.set("n", "<leader>2", "2gt")
vim.keymap.set("n", "<leader>3", "3gt")
vim.keymap.set("n", "<leader>4", "4gt")
vim.keymap.set("n", "<leader>5", "5gt")
vim.keymap.set("n", "<leader>6", "6gt")
vim.keymap.set("n", "<leader>7", "7gt")
vim.keymap.set("n", "<leader>8", "8gt")
vim.keymap.set("n", "<leader>9", "9gt")
vim.keymap.set("n", "<leader>w", ":tabclose<CR>")
vim.keymap.set("n", "<leader>c", ":tabnew<CR>")
