---
src_directory: ../../src/default
work_src_directory: ../../src/default
dotfiles_directory: "{{ lookup('env', 'HOME') }}/.dotfiles/src/default/dotfiles"
dotfiles_files:
  - config/git
  - config/nvim
  - config/skhd
  - config/yabai
  - config/tmux
  - config/fish
  - config/lazygit
  - config/starship.toml
  - config/wezterm
  - zshrc

homebrew_file: "{{ work_src_directory }}/Brewfile.rb"
homebrew_repo: https://github.com/Homebrew/brew
homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

wallpaper_url: https://512pixels.net/downloads/macos-wallpapers-6k/14-Sonoma-Dark.jpg
osx_script: "{{ src_directory }}/osx --no-restart"

ssh_keys_directory: "{{ work_src_directory }}/ssh"
ssh_keys:
  - id_ed25519
ssh_config_files: []
