services:
  'github-vgw': 'github:github.com'
os:
  edit: 'nvim'
gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red       # Red
customCommands:
  - key: 'R'
    command: 'git fetch upstream main && git rebase upstream/main && git push --force-with-lease'
    context: 'localBranches'
  - key: '<C-p>'
    command: "git add -A && git commit --allow-empty-message -m '' && git push"
    context: 'localBranches'
