lastupdatecheck: 0
recentrepos:
- /Users/thomas-delalande/.dotfiles
- /Users/thomas-delalande/dev/work/stryd-services
- /Users/thomas-delalande/dev/work/stryd-frontend
- /Users/thomas-delalande/dev/game-engine
- /Users/thomas-delalande/dev/work/lnd-web-api
- /Users/thomas-delalande/dev/work/stryd-jira-publisher
- /Users/thomas-delalande/dev/DOOM
- /Users/thomas-delalande/dev/work/eskt-2
- /Users/thomas-delalande/dev/work/eskt
- /Users/thomas-delalande/dev/personal/foosball-v5
- /Users/thomas-delalande/dev/personal/football-v3
- /Users/thomas-delalande/dev/personal/timetable
- /Users/thomas-delalande/dev/work/stryd-release-pipeline
- /Users/thomas-delalande/dev/personal/bjj-elo
- /Users/thomas-delalande/dev/tinyclub
- /Users/thomas-delalande/dev/personal/product-db
- /Users/thomas-delalande/dev/work/stryd-infra-account
- /Users/thomas-delalande/dev/personal/game-design-simulator
- /Users/thomas-delalande/dev/personal/vaultwarden
- /Users/thomas-delalande/dev/personal/foosball
- /Users/thomas-delalande/dev/personal/couch
- /Users/thomas-delalande/dev/personal/rengar
- /Users/thomas-delalande/dev/work/stryd-infra
- /Users/thomas-delalande/dev/personal/Balatro
- /Users/thomas-delalande/dev/personal/balatro-ai
- /Users/thomas-delalande/dev/personal/pico8-example
- /Users/thomas-delalande/dev/personal/nesting
- /Users/thomas-delalande/dev/personal/qmk_firmware
- /Users/thomas-delalande/dev/personal/balatro-examples
- /Users/thomas-delalande/dev/personal/pvp-daw
- /Users/thomas-delalande/dev/madcatz/mad-catz-conference
- /Users/thomas-delalande/dev/madcatz/mad-catz-conference2
- /Users/thomas-delalande/dev/madcatz/conference
- /Users/thomas-delalande/dev/personal/lichess/tutorial/hello
- /Users/thomas-delalande/dev/personal/anim-gc
- /Users/thomas-delalande/dev/personal/butter-bot
- /Users/thomas-delalande/dev/yt/low-level-vs-high-level
- /Users/thomas-delalande/dev/languages-comparison
- /Users/thomas-delalande/dev/yt/mobile-ui
- /Users/thomas-delalande/dev/learning-ai
- /Users/thomas-delalande/dev/authn
- /Users/thomas-delalande/dev/holifresh/holifresh-app
- /Users/thomas-delalande/dev/database-ui
- /Users/thomas-delalande/dev/holifresh/holifresh-hfz
- /Users/thomas-delalande/dev/downloaded-git
- /Users/thomas-delalande/dev/learning-kotlin-typescript
- /Users/thomas-delalande/dev/learning-htmx-vs-react
- /Users/thomas-delalande/dev/html-to-kotlin-converter
- /Users/thomas-delalande/dev/learning-kotlin-ssr
- /Users/thomas-delalande/dev/dx
- /Users/thomas-delalande/dev/learning-infinite-craft
- /Users/thomas-delalande/dev/learning-passkeys
- /Users/thomas-delalande/dev/feature-toggle
- /Users/thomas-delalande/dev/kotlin-template
- /Users/thomas-delalande/dev/learning-gradle-tailwind
- /Users/thomas-delalande/dev/poker-pvp
- /Users/thomas-delalande/dev/ktor-websocket-bug-reproduce
- /Users/thomas-delalande/dev/poker
- /Users/thomas-delalande/dev/learning-kotlin-playground
- /Users/thomas-delalande/dev/hower-tall
- /Users/thomas-delalande/dev/dating-app
- /Users/thomas-delalande/dev/stay-focused
- /Users/thomas-delalande/dev/go-htmx-template
- /Users/thomas-delalande/dev/nginx-server
- /Users/thomas-delalande/dev/launchpad-controller-spotify
- /Users/thomas-delalande/dev/zig-raylib
- /Users/thomas-delalande/dev/projects
- /Users/thomas-delalande/dev/zig-playground
- /Users/thomas-delalande/dev/poni-site
- /Users/thomas-delalande/dev/learning-go-ssr-htmx
- /Users/thomas-delalande/dev/learning-k8s-argocd
- /Users/thomas-delalande/dev/featflags
- /Users/thomas-delalande/dev/minecraft-mods
- /Users/thomas-delalande/dev/live-streaming
- /Users/thomas-delalande/dev/.dotfiles
- /Users/thomas-delalande/.raycast/extensions/tmux-sessionizer-raycast
- /Users/thomas-delalande/dev/leptos-tailwind-starter
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: true
ignorewhitespaceindiffview: true
